# Generated by Django 3.2.7 on 2021-10-16 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20211016_1032'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductReview',
        ),
    ]
